#server port configuration
server:
  port: 9095

#profile configuration
profiles:
    active: local

#application name configiration
spring:
  application:
    name: web-bff

#jwt configuration
jwt:
   secret : ${JWT_SECRET}

#retry breaker configuration
resilience4j:
  retry:
    retry-aspect-order: 2
    instances:
      default:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-max-wait-duration: 5s
        retry-exceptions:
#          - feign.RetryableException
#          - java.net.ConnectException
#          - java.io.IOException
#          - java.lang.IllegalStateException
#          - java.lang.RuntimeException
#          - feign.FeignException

#retry breaker configuration
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      default:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-size: 10
        sliding-window-type: count-based
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 80

#actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "health,info,circuitbreakers,retries" 
  endpoint:
    health:
      show-details: always 
  health:
    circuitbreakers:
      enabled: true 
